---
title: "Linear Models"
author: "Stephanie Zhen"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

## Data Cleaning
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

Fitting Linear regression
```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit

summary(fit)
summary(fit)$coeff
coef(fit)
```


Tidy the redults:
```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```

### Take a look at factors/categorical predictors, and refitting model:
```{r}
nyc_airbnb = nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type))

fit_fct = lm(price ~ stars + boro, data = nyc_airbnb)
fit_fct %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)

##broom package helps tidy a lot of outputs. 
## the p-value in broom glance test the global null hypothesis. 
fit_fct %>% 
  broom::glance()
```


## Diagnostics
```{r}
modelr::add_residuals(nyc_airbnb, fit_fct) %>% 
  ggplot(aes(x = boro, y = resid)) +
  geom_violin() +
  ylim(-500, 500)

modelr::add_residuals(nyc_airbnb, fit_fct) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point() +
  ylim(-500, 500)

modelr::add_predictions(nyc_airbnb, fit_fct)
```

## Nesting...interactions
```{r}
fit_interaction = lm(price ~stars * boro + room_type * boro, data = nyc_airbnb)
  
fit_interaction %>% 
  broom::tidy()
```


```{r}
nyc_airbnb %>% 
  filter(boro == "Brooklyn") %>% 
  lm(price ~ stars + room_type, data = .) %>% 
  broom::tidy()
##but don't wan to redo this for every boro
```

Instead try mapping stead
```{r}
nest_lm_res =
  nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models)

nest_lm_res
```


```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(boro == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  nest(data = -neighborhood) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models)

manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```


